### ISSUE TITLE
Email subject

### ISSUE THREAD

**Issue by maeishoj** [andris9/smtp-connection#15]
I was implementing your smtp client when I realized that it does not offer a chance to append a subject to the mail. I wonder why that is. Who wouldn't want to use a subject in their email?

Could this feature be added?

**Comment by raduamarie** [comment]
I have the same problem. lol!

**Comment by andris9** [comment]
smtp-connection only provides SMTP transport layer. The subject is defined in the rfc822 message data and is not part of SMTP. Use [Nodemailer](https://www.npmjs.com/package/nodemailer) if you need a full fledged solution where the rfc822 message is composed instead of you.
