### ISSUE TITLE
Emails are never sent

### ISSUE THREAD

**Issue by Tug** [andris9/smtp-connection#16]
I'm sending transactional emails through Sendgrid using Nodemailer. I have tried using `nodemailer-smtp-transport` as well as `nodemailer-smtp-pool` but in both case I have emails that are never sent. 

The callback of Nodemailer `smtpTransport.sendMail(email, callback);` is never called and no emails are sent. So timeout is not working.

I could not reproduce this bug in my dev environment but it happens fairly often in production (1 every 3 emails) so I have activated the debug option, and this is what I got in those case:
```
SMTP transport 'LOG':  { type: 'created', message: 'New connection #1' }
SMTP transport 'LOG':  { type: 'message',
  message: 'Assigned message to connection #1' }
```
And nothing more.
So it looks like the server does not even respond.

This is the options I have at the moment:
```
{
            host: "smtp.sendgrid.net",
            port: 2525,
            requireTLS: true,
            secure: false, // SSL not supported on port 2525
            auth: {
                user: "MY_USER",
                pass: "MY_PASSWORD"
            },
            debug: true,
            maxConnections: 5,
            maxMessages: 10
}
```

**Comment by Tug** [comment]
To be more precise, in my case, 2 emails are sent concurrently so this is what I really have:
```
SMTP transport 'LOG':  { type: 'created', message: 'New connection #1' }
SMTP transport 'LOG':  { type: 'message',
  message: 'Assigned message to connection #1' }
SMTP transport 'LOG':  { type: 'created', message: 'New connection #2' }
SMTP transport 'LOG':  { type: 'message',
  message: 'Assigned message to connection #2' }
```

**Comment by andris9** [comment]
What version of node are you running in production? After you get the message "Assigned message to connection #x" the client tries to connect to the server. If you do not get any response after that then the connection gets into some undefined state even though it should hit into a timeout and return an error if connection is not established in defined time.

Right now I have no idea what is going on there as I can't reproduce the issue myself – I used the same settings for my own Sendgrid account and sent 50 messages with the pool with no issues whatsoever.

**Comment by Tug** [comment]
Sorry false alarm!
I was able to track down the bug in my code. I was calling a `domain.dispose()` after the end of my request which is probably the cause of all this.
