### ISSUE TITLE
Does not comply to RFC 821 - Simple Mail Transfer Protocol

### ISSUE THREAD

**Issue by vertex** [andris9/smtp-connection#17]
Strange error here when you have a picky SMTP server.   Random `!` marks are getting added into our e-mails at seemingly consistent points (~1000-1500).   After some searching, we found some supporting documentation.  
http://stackoverflow.com/questions/6596517/random-exclamation-marks-in-email-body-generated-using-utl-smtp-in-pl-sql
They suggested that the SMTP protocol requires line breaks after 1000 characters.  
>            text line
>               The maximum total length of a text line including the
>               <CRLF> is 1000 characters (but not counting the leading
>               dot duplicated for transparency).

**Comment by andris9** [comment]
You need to add the line breaks to the data yourself before you pass this to smtp-connection as only you are context-aware enough that you know where you can put the linebreak. If smtp-connection would start to put linebreaks inti the data it would break it
