### ISSUE TITLE
ignoreTLS misleading

### ISSUE THREAD

**Issue by aylusltd** [andris9/smtp-connection#20]
`requireTLS:false` still attempts a TLS connection (and consequently fails on self-signed certificates).

 Program works, don't get me wrong, just had a devil of a time figuring out why `requireTLS:false` didn't seem to do anything.

**Comment by andris9** [comment]
`requireTLS` is a security option. By default TLS is used opportunistically – if the server advertises STARTTLS then it is used (unless you have disabled it by setting `ignoreTLS: true`). If you know that the server uses self signed cert then you could add this cert to the CA list (`options.tls.ca=['self-signed-cert']`).

`requireTLS` option is to make sure that the connection tries to use STARTTLS even if the server does not advertise support for it – maybe the proxying middleman removed STARTTLS server response to force plaintext usage. In this case if secure connection can't be established the connection is deemed as failed and authentication tokens are not sent over unsecure connection.

Anyway, I wouldn't change the current API, it might be slightly confusing but I think in most cases it does exactly what it needs to.
