### ISSUE TITLE
Doesn't seem to work with GANDI SMTP

### ISSUE THREAD

**Issue by jhiver** [andris9/smtp-connection#24]
Here's the debug log, connect callback is never called.

MacBook-Pro-de-JM:server jhiver$ coffee test.coffee 
{ type: 'server',
  message: '220 relay.mail.gandi.net ESMTP Postfix' }
{ type: 'client', message: 'EHLO MacBook-Pro-de-JM.local' }
{ type: 'server',
  message: '250-relay5-d.mail.gandi.net\n250-PIPELINING\n250-SIZE 35651584\n250-VRFY\n250-ETRN\n250-STARTTLS\n250-AUTH PLAIN LOGIN\n250-ENHANCEDSTATUSCODES\n250-8BITMIME\n250 DSN' }
{ type: 'client', message: 'STARTTLS' }
{ type: 'server', message: '220 2.0.0 Ready to start TLS' }
{ type: 'socket', message: 'Connection upgraded' }
{ type: 'client', message: 'EHLO MacBook-Pro-de-JM.local' }
{ type: 'server',
  message: '250-relay5-d.mail.gandi.net\n250-PIPELINING\n250-SIZE 35651584\n250-VRFY\n250-ETRN\n250-AUTH PLAIN LOGIN\n250-ENHANCEDSTATUSCODES\n250-8BITMIME\n250 DSN' }

Test script (coffeescript):

    options =
      "host": "mail.gandi.net",
      "connectionTimeout": 10000,
      "port": 587,
      "secure": false
      "debug": true

    SMTPConnection = require 'smtp-connection'
    connection = new SMTPConnection(options)
    connection.on 'log', (info) -> console.log info

    connection.connect options, ->
      console.log "I AM CONNECTED"

**Comment by andris9** [comment]
I have no idea how coffeescript works. Could you provide an example script using javascript?

**Comment by jhiver** [comment]
Well coffeescript is javascript without all the curly braces parenthesis and semicolons... give it a go someday it's awesome :-) Anyways, here you go below:

    var SMTPConnection, connection, options;

    options = {
      "host": "mail.gandi.net",
      "connectionTimeout": 10000,
      "port": 587,
      "secure": false,
      "debug": true
   };
    
    SMTPConnection = require('smtp-connection');
    
    connection = new SMTPConnection(options);
    
    connection.on('log', function(info) {
      return console.log(info);
    });
    
    connection.connect(options, function() {
      return console.log("I AM CONNECTED");
    });
    
    // ---
    // generated by coffee-script 1.9.2

**Comment by andris9** [comment]
Thanks. Your issue is that `connect` only takes the callback argument but you have `connect(options, func)` while it should be `connect(func)`

**Comment by jhiver** [comment]
Wow, sorry I missed that. Wouldn't it make sense to raise an error when an object is passed instead of a function?

Thanks a bunch!
