### ISSUE TITLE
Un-catchable error ECONNREFUSED

### ISSUE THREAD

**Issue by Karl-Gustav** [andris9/smtp-connection#27]
When I try and run this code on a mac with out an SMPT server the code crashes with the uncatchable error:

    Error: connect ECONNREFUSED
         at errnoException (net.js:905:11)
         at Object.afterConnect [as oncomplete] (net.js:896:19)

Now I understand that this should not work as I don't have a SMTP server on my machine, but I would expect it to call the callback with an error and not crash the entire node app.

The code looks like this:

    var connection = new SMTPConnection();

    try {
        connection.connect(function (err) {});
    } catch (e) {
        console.log(e);
    }

**Comment by andris9** [comment]
You need to set the `error` event handler to catch connection errors

```javascript
var connection = new SMTPConnection();
connection.on('error', function(err){
    console.log('Connection failed');
});
connection.connect(function(){
    console.log('Connection established');
});
```
